import './globals.css'
import Navbar from './components/Navbar'

import { Inter,Poppins,Bebas_Neue, } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
        <html lang="en">
            <body className={`p-0 m-0 w-screen h-[100%] overflow-x-hidden ${inter.className}`}>
                {children}
            </body>
        </html>
  )
}
